export K6_OTEL_EXPORTER_PROTOCOL=http/protobuf
export K6_OTEL_HTTP_EXPORTER_ENDPOINT=127.0.0.1:9090
export K6_OTEL_HTTP_EXPORTER_URL_PATH=/api/v1/otlp/v1/metrics
export K6_OTEL_HTTP_EXPORTER_INSECURE=true
export K6_OTEL_METRIC_PREFIX=k6_
