apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ml-autoscaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jathu06/vjtech-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "vjtech_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres123"
